### PR TITLE
CONJ-4875 add `--net` switch to `test` and `sandbox` subcommands

### PR DESCRIPTION
**Pull request by apotterri**
Adds new cukes for both subcommands, as well as error reporting when starting a container fails.

To verify, read the changes (especially the README updates) and see that the build is green: https://jenkins.conjur.net/job/conjurinc--debify/job/start-errors_20180313/9/

### CODE REVIEW

**Review by izgeri — CHANGES_REQUESTED** [review]
The only question I have is why this update restricts it so that you can't use `--net` and `--link` together. I tried it with a modified version that silences that error (and used both of them), and it works fine.

Things I verified:
- My changes from yesterday to `authn-jwt` still work with this update
- I can remove `docker network connect` and `--link` and just use `--net` instead, and my `authn-jwt` start script still works
- Verified that --net and --link don't work together (ie you get an error if you use both, as designed)
- Ran through example and verified it works as expected

**Comment by apotterri** [comment]
I did that because, for while, the docker folk were talking about deprecating `--link` in favor of just using user-defined networks. I just looked at the current version of the doc, though, and they seemed to have changed direction. Now, using `--link` on a user-defined network adds an alias for the linked host.

I'll remove the restriction.

**Comment by apotterri** [comment]
@izgeri This is ready for another look. Build's green here: https://jenkins.conjur.net/job/conjurinc--debify/job/start-errors_20180313/10/

**Review by izgeri — CHANGES_REQUESTED** [review]
These work:
- The `dev/start.sh` script in `authn-jwt` works with these updates in its current config
- If I update the script to use `--net` instead of `--link` to put the conjur appliance on the token-service network, it works as expected

These don't work (in both cases, I have cloned `conjurinc/authn-jwt` and `cd authn-jwt/dev` before modifying the relevant files and running `./start.sh`):
- If I comment the `docker network connect` in my `authn-jwt` start script and add `--net dev_token-service` to the debify command, Conjur can't resolve the host https://token-service (even though they are on the same network)
debify output:
```
creating container with options {"name"=>"authn-jwt-sandbox", "Image"=>"sha256:b61378064ef4e30498ab9f9f4e71a408d4c407bfb6a868cd368807fa599c6497", "WorkingDir"=>"/src/authn-jwt", "Env"=>["CONJUR_AUTHN_LOGIN=admin", "CONJUR_ENV=appliance", "CONJUR_AUTHN_API_KEY=secret", "CONJUR_ADMIN_PASSWORD=secret"], "HostConfig"=>{"Binds"=>["/Users/gjennings/.ssh/id_rsa:/root/.ssh/id_rsa:ro", "/Users/gjennings/Documents/repos/pcf/authn-jwt:/src/authn-jwt", "/Users/gjennings/tmp/debify/authn-jwt/vendor:/src/authn-jwt/vendor", "/Users/gjennings/tmp/debify/authn-jwt/.bundle:/src/authn-jwt/.bundle"], "Privileged"=>true, "NetworkMode"=>"dev_token-service", "PortBindings"=>{"443/tcp"=>[{"HostPort"=>"8443"}]}}, "NetworkingConfig"=>{"EndpointsConfig"=>{"dev_token-service"=>{"Links"=>["2fcac72a42e6b8188ea790f06160aa37178a67f993e5d657041f4722a1668eb7:token-service"]}}}}
```
- If I:
  - update `dev/docker-compose.yml` to rename the `token-service` service `token-service-nginx`
  - update `start.sh` to `docker-compose up -d token-service-backend token-service-nginx`
  - update `TOKEN_ISSUER_CID` to come from `docker-compose ps -q token-service-nginx` in `start.sh`
  - comment out `docker network connect` in `start.sh`
  - add `--net dev_token-service` to the end of the `debify` command in `start.sh` to connect conjur to the `dev_token-service` network that docker-compose creates

then conjur can't resolve the host https://token-service (even though they are on the same network)
debify output:
```
creating container with options {"name"=>"authn-jwt-sandbox", "Image"=>"sha256:4a6cb0aa42ae4c593f4f332f6f8fbdbc138be67737794b99c5fcf9427c95aa9a", "WorkingDir"=>"/src/authn-jwt", "Env"=>["CONJUR_AUTHN_LOGIN=admin", "CONJUR_ENV=appliance", "CONJUR_AUTHN_API_KEY=secret", "CONJUR_ADMIN_PASSWORD=secret"], "HostConfig"=>{"Binds"=>["/Users/gjennings/.ssh/id_rsa:/root/.ssh/id_rsa:ro", "/Users/gjennings/Documents/repos/pcf/authn-jwt:/src/authn-jwt", "/Users/gjennings/tmp/debify/authn-jwt/vendor:/src/authn-jwt/vendor", "/Users/gjennings/tmp/debify/authn-jwt/.bundle:/src/authn-jwt/.bundle"], "Privileged"=>true, "NetworkMode"=>"dev_token-service", "PortBindings"=>{"443/tcp"=>[{"HostPort"=>"8443"}]}}, "NetworkingConfig"=>{"EndpointsConfig"=>{"dev_token-service"=>{"Links"=>["48562fd34d444ee018da2ea336dcb34c28983d78354d38c18231e78d8b91f89e:token-service"]}}}}
```

In the last version of these changes, I could do either of the last two and have it work. I haven't been able to do a case with both `--net` and `--link` since these updates that is successful.
To check if it is working properly, I am running 
```
export TOKEN=`curl -k "https://localhost:9443/jwt?iss=https://token-service&aud=conjur&role=admin&ip=127.0.0.1"`
curl --cacert tmp/conjur.pem -i -X POST --data $TOKEN https://localhost:8443/api/authn-jwt/token-service/users/admin/authenticate
```
(as described in the `authn-jwt` README) and expecting the last command to send me a conjur access token, but I am getting a 500 error instead.

**Comment by apotterri** [comment]
@izgeri Ok, I figured out what's going on. When `--link src:dest` is used with `--net`, docker adds a network alias `dest` that resolves to `src`. When docker starts a container, it adds the container's short id as a network alias. So, if the `src` of your `--link` link is a short id, the alias works. If you use the container's full id (which is what `dev/start.sh` is doing), the alias does nothing.

If you're used to using `--link` without `--net`, this behavior seems kind of surprising. My latest commit adds code that looks for full container ids in `--link` sources and shortens them (printing a warning when it does so).

I confirmed that when I run `dev/start.sh` with the changes you described, the name `token-service` resolves correctly in the `authn-jwt-sandbox`.

However, when I run 

```
curl --cacert tmp/conjur.pem -i -X POST --data $TOKEN https://localhost:8443/api/authn-jwt/token-service/users/admin/authenticate
```

I'm still seeing a 500. Looking at the server logs, I see 

```
Mar 16 19:08:30 a256234649f5 conjur-authn-jwt: Completed 500 Internal Server Error in 96ms
Mar 16 19:08:30 a256234649f5 conjur-authn-jwt:
Mar 16 19:08:30 a256234649f5 conjur-authn-jwt: OpenSSL::SSL::SSLError (SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed):
Mar 16 19:08:30 a256234649f5 conjur-authn-jwt:
Mar 16 19:08:30 a256234649f5 conjur-authn-jwt: lib/jwk_store.rb:16:in `get'
Mar 16 19:08:30 a256234649f5 conjur-authn-jwt: app/models/authenticator.rb:40:in `validate_token'
Mar 16 19:08:30 a256234649f5 conjur-authn-jwt: app/models/authenticator.rb:24:in `authenticate_token'
Mar 16 19:08:30 a256234649f5 conjur-authn-jwt: app/controllers/authenticate_controller.rb:10:in `post'
Mar 16 19:08:30 a256234649f5 conjur-authn-jwt: 172.18.0.1 - - [16/Mar/2018:19:08:30 +0000] "POST /500 HTTP/1.0" 500 - 0.1577
```

This looks like a problem after it's successfully resolved the name `token-service`.

**Review by izgeri — APPROVED** [review]
I'm not sure what was up with that last 500 error in `authn-jwt`, but I agree these changes aren't the problem (and I wasn't able to replicate, fwiw).

I reran the test cases I had in `authn-jwt` with your updated changes and it all worked fine!

Looks good to merge.

**Pull request merged**
